name: testing workflow variables
on:
  workflow_dispatch:
env:
  cloud: google_cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      - name: "say hello to all"
        run: echo "$greeting $first_name is using $cloud"
        env:
          first_name: dev
