name: context variable

on:
  workflow_dispatch:

env:
  name: dev-sharma

jobs:
  testing_context_variable:
    runs-on: ubuntu-latest

    steps:
      - name: testing context variable
        run: |
          echo "my name is $name"
          echo "working on repository: ${{ github.repository }}"
          echo "triggered by user: ${{ github.actor }}"
