name: input-variable

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "enter number 1"
        required: true
        default: '0'
      number2:
        description: "enter number 2"
        required: true
        default: '0'

jobs:
  testing_input_variable:
    runs-on: ubuntu-latest

    steps:
      - name: add numbers
        id: sum
        run: |
          result=$((${{ inputs.number1 }} + ${{ inputs.number2 }}))
          echo "sum=$result" >> $GITHUB_OUTPUT

      - name: display sum
        run: echo "sum of ${{ inputs.number1 }} and ${{ inputs.number2 }} is ${{ steps.sum.outputs.sum }}"
